export const TYPE_CONFIG = {
  fundraiser: {
    accentColor: '#635bff',
    accentGradient: 'linear-gradient(135deg, #635bff, #3b82f6)',
    color: '#635bff',
    gradient: 'linear-gradient(135deg, #635bff, #3b82f6)',
    bgAccent: 'rgba(99,91,255,0.08)',
    borderAccent: 'rgba(99,91,255,0.20)',
    label: 'Fundraiser',
    emoji: '\u{1F31F}',
    supportLabel: 'Donate Now',
    supportIcon: '\u{1F31F}',
    amountLabel: 'Donate',
    raisedLabel: 'raised',
    goalLabel: 'goal',
    supportersLabel: 'Donors',
    actionVerb: 'Donating',
    successMsg: 'Thank you for your donation! Every contribution brings us closer to the goal.',
    securityMsg: '100% secure donation',
    shareMsg: 'Help us reach more donors!',
    ctaText: 'Donate Now',
    tagline: 'Rally support for your cause',
    categories: ['Medical & Healthcare', 'Education', 'Emergency & Crisis', 'Community Development', 'Animal Welfare', 'Arts & Culture', 'Other'],
    storyLabel: 'Your Story',
    storyPlaceholder: 'Tell supporters what you need help with, why it matters, and what a difference their contribution will make\u2026',
    goalFieldLabel: 'Fundraising Goal (\u20A6)',
    showFundUsage: true,
    showEventDate: false,
    showTipSuggestions: false,
    step2Heading: 'Tell Your Story',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?fit=crop&w=1200&q=80',
  },
  occasion: {
    accentColor: '#a855f7',
    accentGradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
    bgAccent: 'rgba(168,85,247,0.08)',
    borderAccent: 'rgba(168,85,247,0.20)',
    label: 'Occasion Gift',
    emoji: '\u{1F389}',
    supportLabel: 'Send a Gift',
    supportIcon: '\u{1F389}',
    amountLabel: 'Gift',
    raisedLabel: 'gifted',
    goalLabel: 'goal',
    supportersLabel: 'Gift Givers',
    actionVerb: 'Sending gift',
    successMsg: 'Your gift has been sent with love! Wishing them a wonderful celebration.',
    securityMsg: 'Gifts sent securely with love',
    shareMsg: 'Spread the celebration!',
    ctaText: 'Send a Gift',
    tagline: 'Create your gift collection page',
    categories: ['Wedding', 'Birthday', 'Anniversary', 'Baby Shower', 'Graduation', 'Retirement', 'Other Celebration'],
    storyLabel: 'Message to Your Guests',
    storyPlaceholder: 'Write a warm message to your guests \u2014 tell them about the occasion, what the gifts mean to you, and how they can celebrate with you\u2026',
    goalFieldLabel: 'Gift Collection Target (\u20A6) \u2014 optional',
    showFundUsage: false,
    showEventDate: true,
    showTipSuggestions: false,
    step2Heading: 'Your Celebration Story',
    heroImage: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?fit=crop&w=1200&q=80',
  },
  tips: {
    accentColor: '#06b6d4',
    accentGradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    bgAccent: 'rgba(6,182,212,0.08)',
    borderAccent: 'rgba(6,182,212,0.20)',
    label: 'Tips',
    emoji: '\u{1F4B8}',
    supportLabel: 'Show Some Love',
    supportIcon: '\u{1F4B8}',
    amountLabel: 'Tip',
    raisedLabel: 'received',
    goalLabel: 'target',
    supportersLabel: 'Supporters',
    actionVerb: 'Sending tip',
    successMsg: "You're amazing! Your tip means the world to them. Thank you for showing love.",
    securityMsg: 'Tips sent instantly & securely',
    shareMsg: 'Share the love!',
    ctaText: 'Show Love',
    tagline: 'Let your fans show love',
    categories: ['Content Creator', 'Music / DJ', 'Performer / Artist', 'Freelancer', 'Food & Hospitality', 'Education / Tutoring', 'Other'],
    storyLabel: 'About You',
    storyPlaceholder: 'Tell your supporters who you are, what you do, and why their tips make a difference. Be personal and genuine!',
    goalFieldLabel: 'Monthly Tip Target (\u20A6) \u2014 optional',
    showFundUsage: false,
    showEventDate: false,
    showTipSuggestions: true,
    step2Heading: 'Introduce Yourself',
    heroImage: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?fit=crop&w=1200&q=80',
  },
} as const;

export type CollectionType = keyof typeof TYPE_CONFIG;
